#!/bin/bash

# Render SMTP Environment Variables Setup Script
# Run this script to add SMTP environment variables to your Render service

echo "🚀 Forage Stores Backend - SMTP Setup for Render"
echo "=================================================="
echo ""
echo "To set up Gmail SMTP on Render, add these environment variables in your Render dashboard:"
echo ""
echo "Environment Variables to Add:"
echo "=============================="
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "SMTP_USER=your-gmail@gmail.com"
echo "SMTP_PASS=your-16-character-app-password"
echo "SMTP_FROM=your-gmail@gmail.com"
echo ""
echo "📋 Instructions:"
echo "=================="
echo "1. Go to your Render dashboard"
echo "2. Select your backend service"
echo "3. Go to 'Environment' tab"
echo "4. Add each variable above with your actual values"
echo "5. Deploy your service"
echo ""
echo "🔐 Gmail App Password Setup:"
echo "============================="
echo "1. Enable 2-Factor Authentication on your Gmail account"
echo "2. Go to https://myaccount.google.com/"
echo "3. Security → App passwords"
echo "4. Generate an app password for 'Mail'"
echo "5. Use the 16-character password as SMTP_PASS"
echo ""
echo "🧪 Testing:"
echo "============"
echo "After deployment, test your SMTP setup by calling:"
echo "POST /auth/test-email"
echo "Body: { \"email\": \"your-test-email@example.com\" }"
echo ""
echo "✅ You're all set! Your backend can now send emails via Gmail SMTP (free tier)."
